spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:~/h2/resource-torrent-downloader;AUTO_SERVER=TRUE
  thymeleaf:
    cache: false
server:
  http2:
    enabled: true
  port: 10111
